sudo: required
services:
  - docker
before_script:
  - tag="${TRAVIS_TAG:-latest}"
  - image_name="$(echo "${TRAVIS_REPO_SLUG}" | cut -d '/' -f 2)"
  - docker_org="actions"
  - version=1.10
  - package_version=${version}-41.1
script:
  - docker build --build-arg REQUIRED_PACKAGES="netcat=${package_version}" -t ${docker_org}/${image_name} .
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  - provider: script
    script: docker push ${docker_org}/${image_name}:latest
    on:
      branch: master
  - provider: script
    script: docker tag ${docker_org}/${image_name}:latest ${docker_org}/${image_name}:${version} && docker push ${docker_org}/${image_name}:${version}
    on:
      branch: master
      tags: true